# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - docker-web-app-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://classactivity3.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0ce27dc7ae7747fd83be3ec6b9e4ac4a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d3a06a61b32744cb9519332fcd9ec4f2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: classactivity3.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0ce27dc7ae7747fd83be3ec6b9e4ac4a }}/demo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'docker-web-app-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ea3ac44c8a004d1096991580837263db }}
        images: 'classactivity3.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0ce27dc7ae7747fd83be3ec6b9e4ac4a }}/demo:${{ github.sha }}'